spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: userapp
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
server:
  port: 8080